# TransformationGraph, ActColony
WEIGHT = 1
NODE_DISTANCE_THRESHOLD = 4

# Ant
ALPHA = 1
BETA = 2
EVAPORATION_RATE = 0.4
LENGTH_OF_PATH = 3
RANDOM_CHOICE_RATE = 0.5

# AntColony
INITIAL_PHEROMONE = 1
ITERATION_BUDGET = 10
ANT_COUNT = 50
